# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
gems:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate

# Site settings
title: joh.fi
subtitle: ""
email: haaja@iki.fi
name: Janne Haapsaari
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://joh.fi" # the base hostname & protocol for your site
#url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"

permalink: /:year/:month/:day/:title.html

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "tomorrow-night"

exclude: [deploy.sh, README.md, Gemfile, Gemfile.lock, circle.yml, vendor]

sass:
    style: compressed

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
disqus_shortname: haaja

# Google analytics
ga_tracking_id: "UA-9365169-1"

# Category descriptions (for archive pages)
#descriptions:
#  - cat: jekyll
#    desc: "Posts describing Jekyll setup techniques."
#
#  - cat: dummy
#    desc: "Just some placeholder posts, lorem ipsum and the rest."


# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: twitter
    username: "@jhaaps"
    url: https://twitter.com/jhaaps
    desc: Follow me on Twitter
    share: true

  - name: Facebook
    icon: facebook
    username: Janne Haapsaari
    url: https://www.facebook.com/jhaapsaari
    desc: Friend me on Facebook
    share: true

  - name: GitHub
    icon: github
    username: haaja
    url: https://github.com/haaja
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Janne Haapsaari
    url: https://fi.linkedin.com/in/jannehaapsaari
    desc: Connect with me on LinkedIn
    share: true

  - name: Google+
    icon: google-plus
    username:
    url:
    desc: Add me to your Circles
    share: false

  - name: YouTube
    icon: youtube
    username:
    url:
    desc: Subscribe on YouTube
    share: false

  - name: Instagram
    icon: instagram
    username:
    url:
    desc: Follow me on Instagram
    share: false

  - name: Pinterest
    icon: pinterest
    username:
    url:
    desc: Follow me on Pinterest
    share: false

  - name: SoundCloud
    icon: soundcloud
    username:
    url:
    desc: Follow me on SoundCloud
    share: false

  - name: Tumblr
    icon: tumblr
    username:
    url:
    desc: Follow me on Tumblr
    share: false

  - name: Steam
    icon: steam
    username:
    url:
    desc: Friend me on Steam
    share: false

  - name: Dribbble
    icon: dribbble
    username:
    url:
    desc: Follow me on Dribble
    share: false

  - name: Vimeo
    icon: vimeo-square
    username:
    url:
    desc: Follow me on Vimeo
    share: false

  - name: Vine
    icon: vine
    username:
    url:
    desc: Follow me on Vine
    share: false

  - name: Reddit
    icon: reddit
    username:
    url:
    desc: Share to Reddit
    share: true

  - name: "Hacker News"
    icon: hacker-news
    username:
    url:
    desc: Share to Hacker News
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

#    os_repo: "https://github.com/RichardLitt/wordhoardpress.com"
#    os_rcs_type: "git"
#    os_src: "git@github.com:RichardLitt/wordhoardpress.com.git"
